import React, { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Check, ChevronDown, CircleHelp, Clock3, Footprints, Heart, History, House, Link2, LoaderCircle, Menu, MessageCircle, MoreHorizontal, Pause, Play, Plus, Send, Settings2, ShieldCheck, Sparkles, Sun, Volume2, Wallet, X } from 'lucide-react';
import type { AppState, Charter, Command } from './types';

type Page = 'today' | 'agreement' | 'activity' | 'connections';
type Modal = 'lab' | 'authorize' | 'reset' | null;
const money = (paise: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(paise / 100);
const pretty = (value: string) => value.toLowerCase().replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());
const clock = (time: string) => new Date(time).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Kolkata' });
const scenarioOptions = [
  ['conflict', 'A meeting runs late', 'A calendar conflict creates a smaller, free way back.'],
  ['verified_miss', 'A confirmed missed session', 'Simulated attendance confirms a lapse. Your agreement decides the next action.'],
  ['ambiguous', 'An uncertain attendance signal', 'Missing data is not a missed session. The agent checks in.'],
  ['injury', 'An injury is mentioned', 'Health takes priority. The agent pauses recovery actions.'],
  ['clear', 'An ordinary day', 'No intervention is needed. Sometimes support means staying quiet.'],
  ['payment_failure', 'A demo payment fails', 'Test how the agent explains and handles a failed payment.'],
  ['order_failure', 'A booking fails after payment', 'Test reconciliation and a simulated refund.'],
  ['quiet_hours', 'Something happens in quiet hours', 'See the agreement protect your downtime.'],
] as const;

function Doodle({ compact = false }: { compact?: boolean }) {
  return <svg className={compact ? 'doodle compact' : 'doodle'} viewBox="0 0 310 220" fill="none" aria-hidden="true">
    <path d="M32 198c26-39 54-50 71-40 26 16-4 30 17 42 34 19 121-8 114-45-5-25-57-20-50-47 4-17 29-26 51-31" stroke="currentColor" strokeWidth="2" strokeDasharray="5 7" strokeLinecap="round" />
    <path d="M42 198h228M54 190l7-5 7 5M262 173l-8 8 8 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    <circle cx="224" cy="49" r="24" fill="#d9a853" stroke="currentColor" strokeWidth="1.8" />
    <path d="M224 9V2M224 96v-8M262 50h9M177 50h9M195 20l-6-7M254 21l6-7M194 79l-5 6M253 79l6 7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
    <path d="M214 51c5 7 15 7 21 0" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
    <circle cx="215" cy="43" r="1.5" fill="currentColor" /><circle cx="234" cy="43" r="1.5" fill="currentColor" />
    <path d="M128 57c-3-7-13-11-20-5-9 8-1 24 16 30 19-10 26-24 18-30-5-4-11-3-14 5Z" fill="#e9c5b4" stroke="currentColor" strokeWidth="1.6" />
    <path d="M64 133c-2-10 1-19 8-27m-8 18c-14 0-19-6-20-16 11 0 19 5 20 16Zm1-2c11-1 16-7 16-17-10 1-16 7-16 17Z" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" />
    <path d="m108 182 7-9 8 7-7 9-8-7Zm53-47 8-9 7 7-7 8-8-6Z" fill="#b45433" />
  </svg>;
}

function ModalBox({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  const box = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const prior = document.activeElement as HTMLElement | null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    box.current?.focus();
    const key = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
      if (event.key === 'Tab' && box.current) {
        const elements = [...box.current.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')];
        const first = elements[0]; const last = elements.at(-1);
        if (event.shiftKey && (document.activeElement === first || document.activeElement === box.current)) { event.preventDefault(); last?.focus(); }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
      }
    };
    document.addEventListener('keydown', key);
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener('keydown', key); prior?.focus(); };
  }, [close]);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div className="modal" ref={box} role="dialog" aria-modal="true" aria-labelledby="modal-title" tabIndex={-1}>
    <div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X size={20} /></button></div>{children}
  </div></div>;
}

export default function App() {
  const [state, setState] = useState<AppState | null>(null);
  const [page, setPage] = useState<Page>('today');
  const [modal, setModal] = useState<Modal>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [scenario, setScenario] = useState('conflict');
  const [message, setMessage] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [voiceBusy, setVoiceBusy] = useState(false);
  const [voiceUrl, setVoiceUrl] = useState<string | null>(null);
  const endOfChat = useRef<HTMLDivElement>(null);
  const initialChat = useRef(true);
  async function refresh() {
    try { setError(''); const response = await fetch('/api/state'); if (!response.ok) throw new Error('Could not load your space.'); setState(await response.json()); }
    catch (e) { setError(e instanceof Error ? e.message : 'Connection failed. Please try again.'); }
  }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (initialChat.current) { initialChat.current = false; return; } endOfChat.current?.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); }, [state?.messages.length]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4200); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => () => { if (voiceUrl) URL.revokeObjectURL(voiceUrl); }, [voiceUrl]);
  async function gnaniVoice(messageId: string) {
    if (!state || voiceBusy) return;
    setVoiceBusy(true); setError('');
    try {
      const response = await fetch('/api/voice', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messageId, language: state.charter.language }) });
      if (!response.ok) { const data = await response.json(); throw new Error(data.error || 'Gnani voice is not available yet.'); }
      const nextVoice = URL.createObjectURL(await response.blob());
      setVoiceUrl(previous => { if (previous) URL.revokeObjectURL(previous); return nextVoice; });
      const connection = await fetch('/api/state'); if (connection.ok) setState(await connection.json());
    } catch (e) { setError(e instanceof Error ? e.message : 'Voice request failed. Browser voice is available.'); }
    finally { setVoiceBusy(false); }
  }
  async function command(input: Command, success?: string): Promise<boolean> {
    if (busy) return false;
    setBusy(true); setError('');
    try {
      const response = await fetch('/api/command', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...input, requestId: crypto.randomUUID() }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'That action could not be completed.');
      setState(data); if (success) setToast(success); return true;
    } catch (e) { setError(e instanceof Error ? e.message : 'Connection lost. Please try again.'); return false; }
    finally { setBusy(false); }
  }
  function navigate(next: Page) { setPage(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const nav = [{ id: 'today' as Page, label: 'Today', icon: House }, { id: 'agreement' as Page, label: 'My agreement', icon: ShieldCheck }, { id: 'activity' as Page, label: 'Activity', icon: History }, { id: 'connections' as Page, label: 'Connections', icon: Link2 }];
  if (!state) return <div className="loading-screen"><div className="brand">kal se nahi<span>®</span></div>{error ? <><p role="alert">{error}</p><button className="button primary" onClick={refresh}>Try again</button></> : <><LoaderCircle className="spin" /><p>Making a little room for today…</p></>}</div>;
  const charter = state.charter;
  const selected = state.actions.find(a => a.id === state.episode.selectedActionId);
  const active = charter.active && !charter.paused && !charter.healthPaused;
  const arranged = state.episode.status === 'ARRANGED';
  const completed = ['SELF_REPORTED', 'VERIFIED_RESTART'].includes(state.episode.status);
  const needsConfirmation = state.episode.status === 'CONFIRMATION_REQUIRED';
  const reconcile = state.episode.status === 'RECONCILIATION_REQUIRED';
  const closeModal = () => setModal(null);
  const statusText = !charter.active ? 'Let’s make a plan' : charter.healthPaused ? 'Taking a health break' : charter.paused ? 'Your space is paused' : state.grant?.active ? 'Agreement active' : 'Ready when you are';
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'mobile-open' : ''}`}>
      <button className="brand brand-button" onClick={() => navigate('today')} aria-label="Kal Se Nahi home">kal se nahi<span>®</span><small>ONE SMALL COMEBACK.</small></button>
      <nav aria-label="Main navigation">{nav.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'selected' : ''}`} onClick={() => navigate(item.id)} aria-current={page === item.id ? 'page' : undefined}><item.icon size={19} strokeWidth={1.6} /><span>{item.label}</span>{page === item.id && <span className="nav-dot" />}</button>)}</nav>
      <div className="sidebar-note"><span className="small-star">✳</span><p>Progress has<br />room for pauses.</p><small>We’re here for the way back.</small></div>
      <button className="lab-link" onClick={() => { setModal('lab'); setMobileOpen(false); }}><Settings2 size={17} /><span>Explore the demo</span><ArrowUpRight size={15} /></button>
      <div className="profile"><div className="avatar">{charter.name.slice(0, 1).toUpperCase()}</div><div><strong>{charter.name || 'Your space'}</strong><small>A fresh start, whenever.</small></div><button className="icon-button" aria-label="Edit your agreement" onClick={() => navigate('agreement')}><MoreHorizontal size={18} /></button></div>
    </aside>
    {mobileOpen && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <div className="workspace">
      <header className="topbar"><div><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><span className="breadcrumb">Your space <span>/</span> {nav.find(n => n.id === page)?.label}</span></div><div className="topbar-right"><span className="demo-tag">DEMO</span><span className="demo-date">23 Sep 2026 · 6:15 pm IST</span><button className="icon-button" aria-label="About this demo" onClick={() => setModal('lab')}><CircleHelp size={18} /></button></div></header>
      <main>
        {error && <div className="error-banner" role="alert"><span>{error}</span><button onClick={() => setError('')} aria-label="Dismiss error"><X size={16} /></button></div>}
        {page === 'today' && <>
          <section className="hero"><div><div className="eyebrow"><Sun size={15} /> A LITTLE SPACE FOR YOU</div><h1>A little today.<br />Goes a <em>long way.</em></h1><p>Missed a day? Life happened. Let’s find your way back,<br className="desktop-break" /> one small, doable step at a time.</p></div><Doodle /></section>
          {!charter.active && <section className="setup-banner"><div className="setup-icon"><ShieldCheck size={22} /></div><div><strong>Your pace. Your limits. Your say.</strong><p>Start with a simple agreement so your agent knows what’s okay.</p></div><button className="button primary" onClick={() => navigate('agreement')}>Make my agreement <ArrowRight size={16} /></button></section>}
          {(charter.paused || charter.healthPaused) && <section className="pause-banner"><Heart size={20} /><div><strong>{charter.healthPaused ? 'Rest belongs in the plan.' : 'Everything can wait a little.'}</strong><p>{charter.healthPaused ? 'Recovery actions are paused for your health. Come back when it feels right.' : 'Your agent is paused. Resume whenever you are ready.'}</p></div><button className="button secondary" disabled={busy} onClick={() => command(charter.healthPaused ? { type: 'HEALTH_PAUSE', paused: false } : { type: 'RESUME' })}> {charter.healthPaused ? 'End health pause' : 'Resume'} <Play size={14} /></button></section>}
          <div className="today-grid"><div className="main-column">
            <section className="routine-card"><div className="section-overline">THE THING YOU’RE SHOWING UP FOR <span className={`status-pill ${active ? 'green' : ''}`}><span />{statusText}</span></div><div className="routine-main"><div className="routine-icon"><Footprints size={26} strokeWidth={1.5} /></div><div><h2>{charter.routine}</h2><p><Clock3 size={13} /> {charter.days.join(', ')} <span>·</span> {charter.time} IST</p></div><button className="text-button" onClick={() => navigate('agreement')}>Edit <ArrowUpRight size={14} /></button></div><div className="routine-foot"><span><span className="mini-dot" /> A {charter.fallbackMinutes}-minute fallback always counts.</span><span>{charter.autonomy === 'L3' ? 'Acts within your agreement' : 'Asks before arranging'}</span></div></section>
            <section className="conversation-card"><div className="section-heading"><div><div className="agent-mark">k.</div><div><h2>A little check-in</h2><p>Your comeback companion</p></div></div><span className="live-label"><span /> {busy ? 'Thinking' : 'Here for you'}</span></div>
              <div className="chat-scroll" aria-live="polite" aria-relevant="additions text">{state.messages.map((m, index) => <div key={m.id} className={`chat-message ${m.role}`}><div className="message-meta">{m.role === 'agent' ? 'Kal Se Nahi' : 'You'}<span>{clock(m.at)}</span>{m.source === 'local_model' && <span>Local model</span>}</div><div className="message-bubble">{m.text}</div>{m.role === 'agent' && index === state.messages.length - 1 && <div className="voice-actions">{typeof window.speechSynthesis !== 'undefined' && <button className="read-aloud" onClick={() => { window.speechSynthesis.cancel(); const speech = new SpeechSynthesisUtterance(m.text); speech.lang = charter.language; window.speechSynthesis.speak(speech); }}><Volume2 size={13} /> Browser voice</button>}<button className="read-aloud gnani-voice" disabled={voiceBusy} title="Sends this displayed reply to Gnani and may use account credits." onClick={() => void gnaniVoice(m.id)}><Volume2 size={13} /> {voiceBusy ? 'Preparing Gnani…' : 'Listen with Gnani'}</button></div>}</div>)}{busy && <div className="thinking"><span /><span /><span /><span className="sr-only">Your agent is responding</span></div>}<div ref={endOfChat} /></div>
              <div className="quick-replies"><button disabled={busy} onClick={() => command({ type: 'CHAT', message: 'I only have ten minutes today.' })}>I’ve got 10 minutes</button><button disabled={busy} onClick={() => command({ type: 'CHAT', message: 'I need a break today.' })}>I need a breather</button><button disabled={busy} onClick={() => command({ type: 'CHAT', message: 'What can you do for me?' })}>How does this work?</button></div>
              <form className="chat-input" onSubmit={async e => { e.preventDefault(); if (message.trim() && await command({ type: 'CHAT', message: message.trim() })) setMessage(''); }}><label className="sr-only" htmlFor="chat-message">Message your agent</label><input id="chat-message" value={message} maxLength={1500} onChange={e => setMessage(e.target.value)} placeholder="Tell me what today looks like…" disabled={busy} /><button type="submit" className="send-button" disabled={busy || !message.trim()} aria-label="Send message"><Send size={17} /></button></form><div className="chat-foot">Hindi, Hinglish or English. A sentence is enough. <span>Text conversation · local demo</span></div>
            </section>
            {(selected || !['PROTECTED', 'PAUSED', 'HEALTH_PAUSED', 'QUIET_HOURS'].includes(state.episode.status)) && <section className="next-step-card"><div className="section-overline">YOUR NEXT SMALL STEP <span className="tiny-tag">{pretty(state.episode.status)}</span></div>{completed ? <div className="completion"><div><Check size={23} /></div><h2>You came back. That counts.</h2><p>{state.episode.status === 'SELF_REPORTED' ? 'Marked by you. Self-reported progress is kept separate from attendance proof.' : 'Recorded with simulated partner attendance. This is demo evidence.'}</p></div> : <><h2>{selected?.title || 'There’s a smaller way in.'}</h2><p>{selected?.description || state.episode.reason || 'Choose an option that fits the day you actually have.'}</p>{needsConfirmation && <div className="confirmation-strip"><span>{selected ? `${money(selected.amountPaise)} demo ${selected.amountPaise ? 'payment' : 'cost'} · ${selected.durationMinutes} minutes` : 'Review this action before it is arranged.'}</span><button className="button primary" disabled={busy} onClick={() => command({ type: 'CONFIRM_ACTION' })}>Confirm this step <ArrowRight size={15} /></button></div>}{arranged && !reconcile && <div className="action-buttons"><button className="button primary" disabled={busy} onClick={() => command({ type: 'COMPLETE', source: 'self_report' })}><Check size={16} /> I did it</button>{charter.evidenceSources.includes('attendance') && <button className="button secondary" disabled={busy} onClick={() => command({ type: 'COMPLETE', source: 'demo_attendance' })}>Simulate attendance proof</button>}<p className="fine-print">“I did it” records your own report; it does not create verified attendance.</p></div>}{reconcile && <div className="reconcile-note"><p>The demo booking needs reconciliation. Check the outcome and return any captured demo amount.</p><button className="button primary" disabled={busy} onClick={() => command({ type: 'RECONCILE' })}>Reconcile demo payment</button></div>}{!arranged && !needsConfirmation && !reconcile && !state.episode.snoozed && <div className="recovery-options">{state.actions.map(a => <button key={a.id} disabled={busy || !active || !charter.allowedActionIds.includes(a.id)} onClick={() => command({ type: 'SELECT_ACTION', actionId: a.id })}><div className="option-icon">{a.kind === 'fallback' ? <House size={19} /> : <Footprints size={19} />}</div><div><strong>{a.title}</strong><small>{a.durationMinutes} min · {a.amountPaise ? `${money(a.amountPaise)} demo credit` : 'Free'}</small></div><ArrowUpRight size={17} /></button>)}</div>}{!state.episode.snoozed && !arranged && !reconcile && <button className="text-button gentle" disabled={busy} onClick={() => command({ type: 'SNOOZE' })}>Not today. Give me some space.</button>}</>}</section>}
          </div><aside className="right-column">
            <section className="credit-card"><div className="card-icon"><Wallet size={19} /></div><div className="section-overline">A LITTLE HELP, SET ASIDE</div><h2>{charter.mode === 'none' ? 'No money.<br />Still progress.' : charter.mode === 'stake' ? 'Your stake.<br />Your rules.' : 'Your comeback<br />has a cushion.'}</h2><div className="credit-amount">{money(charter.mode === 'stake' ? Math.max(0, charter.weeklyStakeCapPaise - state.stakeSpentPaise) : Math.max(0, charter.budgetPaise - state.spentPaise))}<span>{charter.mode === 'stake' ? 'remaining demo stake cap' : 'remaining demo credit'}</span></div><div className="credit-meter"><span style={{ width: `${Math.max(0, Math.min(100, 100 * (1 - state.spentPaise / Math.max(1, charter.budgetPaise))))}%` }} /></div><p>{charter.mode === 'none' ? 'Your agreement allows free actions only.' : 'For the small things that make restarting easier. Always within your limits.'}</p><div className="credit-divider" /><div className="credit-limits"><span>Per action</span><strong>{money(charter.maxActionPaise)} max</strong></div><div className="credit-limits"><span>Permission</span><strong>{state.grant?.active ? 'Demo grant active' : 'Not granted'}</strong></div><button className="text-button" onClick={() => navigate('agreement')}>See your agreement <ArrowRight size={15} /></button><small className="credit-disclaimer">Simulation only. No wallet or real funds.</small></section>
            <section className="gentle-card"><span className="small-star">✳</span><blockquote>“You don’t have to<br />start over.<br /><em>Just start smaller.</em>”</blockquote><p>A NOTE FOR TODAY</p></section>
            <section className="demo-invite"><div><Settings2 size={16} /><span>Take it for a spin</span></div><p>Make a meeting run late. Miss a session. See how your agent responds.</p><button className="text-button" onClick={() => setModal('lab')}>Try a scenario <ArrowRight size={15} /></button></section>
          </aside></div>
        </>}
        {page === 'agreement' && <><PageIntro eyebrow="THE PLAN IS YOURS" title={<>A little structure.<br /><em>A lot of say.</em></>} description="Tell your agent what matters, where it can help, and where to draw the line." /><Agreement key={charter.version} state={state} busy={busy} onSave={async draft => { if (await command({ type: 'SAVE_CHARTER', charter: draft }, 'Your agreement is saved. Review your demo permission next.')) setModal('authorize'); }} /><section className="permission-card"><div><ShieldCheck size={25} /><h2>Your permission is a separate choice.</h2><p>{state.grant?.active ? `Demo permission is active for agreement version ${state.grant.charterVersion}. You can withdraw it at any time.` : 'Saving your preferences does not grant payment permission. Review the limits and explicitly authorise the demo.'}</p></div><div className="action-buttons"><button className="button primary" disabled={busy || !charter.active || Boolean(state.grant?.active)} onClick={() => setModal('authorize')}>{state.grant?.active ? 'Demo permission active' : 'Review demo permission'}<ShieldCheck size={16} /></button>{state.grant?.active && <button className="button secondary" disabled={busy} onClick={() => command({ type: 'REVOKE' }, 'Demo permission withdrawn.')}>Withdraw permission</button>}</div><div className="control-row"><button className="text-button" disabled={busy || !charter.active} onClick={() => command({ type: charter.paused ? 'RESUME' : 'PAUSE' })}>{charter.paused ? <Play size={15} /> : <Pause size={15} />}{charter.paused ? 'Resume companion' : 'Pause companion'}</button><button className="text-button" disabled={busy || !charter.active} onClick={() => command({ type: 'HEALTH_PAUSE', paused: !charter.healthPaused })}><Heart size={15} />{charter.healthPaused ? 'End health pause' : 'Take a health break'}</button></div></section></>}
        {page === 'activity' && <><PageIntro eyebrow="NOTHING BEHIND THE CURTAIN" title={<>Every step.<br /><em>In the open.</em></>} description="See what your companion noticed, decided, and did—with every demo payment accounted for." /><div className="activity-toolbar"><span>{state.audit.length} recorded events <span className="tiny-tag">SIMULATED</span></span><a className="button secondary" href="/api/export" download><ArrowDownToLine size={16} /> Export demo audit</a></div>{state.receipts.length > 0 && <section className="receipt-panel"><h2>Demo receipts</h2>{state.receipts.map(r => <div className="receipt" key={r.id}><Wallet size={19} /><div><strong>{r.merchant}</strong><small>{r.id} · {clock(r.at)} · simulated</small></div><span className="tiny-tag">{pretty(r.status)}</span><strong>{money(r.amountPaise)}</strong></div>)}{reconcile && <button className="button primary" disabled={busy} onClick={() => command({ type: 'RECONCILE' })}>Reconcile outstanding demo payment</button>}</section>}<section className="audit-panel">{state.audit.length ? [...state.audit].reverse().map(a => <article className="audit-item" key={a.id}><div className="audit-node"><Check size={12} /></div><div><div className="audit-meta">{clock(a.at)} · agreement v{a.charterVersion} {a.simulated && <span>SIMULATED</span>}</div><h3>{a.title}</h3><p>{a.detail}</p></div></article>) : <div className="empty-state"><History size={28} /><h2>A fresh page.</h2><p>Your agent’s decisions will appear here when you make your agreement or run a scenario.</p><button className="button secondary" onClick={() => setModal('lab')}>Explore a scenario</button></div>}</section></>}
        {page === 'connections' && <><PageIntro eyebrow="THE HELP BEHIND THE HELP" title={<>Connected by design.<br /><em>Honest by default.</em></>} description="This local demo uses simulated partner services. Each connection below tells you exactly what is running." /><div className="connection-grid">{state.rails.map(rail => <section className="connection-card" key={rail.id}><div className="connection-top"><div className="connection-icon"><Link2 size={20} /></div><span className="tiny-tag">{pretty(rail.status)}</span></div><h2>{rail.name}</h2><p>{rail.detail}</p><div className="connection-bottom"><span className="mini-dot" />{rail.configured ? 'Configuration detected — see status above' : 'No live credentials configured'}</div></section>)}</div><section className="connection-note"><MessageCircle size={22} /><div><h2>Conversation that stays clear about its source.</h2><p>{state.planner}. The policy engine controls actions and checks your agreement on every step. “Browser voice” reads messages aloud using your browser’s built-in voice; it is separate from a Gnani integration.</p><p>Microphone input is not enabled in this build. You can type in Hindi or English.</p></div></section><section className="connection-note"><Clock3 size={22} /><div><h2>A demo clock. Real decisions.</h2><p>Scenario time is fixed to 23 September 2026, 6:15 pm IST. The demo runs when you send a message or start a scenario; it does not monitor your real calendar or attendance in the background.</p><button className="text-button" onClick={() => setModal('lab')}>Explore scenarios <ArrowRight size={15} /></button></div></section></>}
        <footer className="page-footer"><span>Made for the days that don’t go to plan.</span><span>Kal Se Nahi <span className="footer-flower">✳</span></span></footer>
      </main>
    </div>
    {voiceUrl && <audio className="voice-player" autoPlay controls aria-label="Gnani voice playback" src={voiceUrl} />}
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}
    {modal === 'lab' && <ModalBox title="A day doesn’t always go to plan." close={closeModal}><p className="modal-description">Try a situation and watch your companion work through it. All signals, payments and attendance evidence in this demo are simulated.</p><label className="field-label" htmlFor="scenario">Choose a scenario</label><select id="scenario" value={scenario} onChange={e => setScenario(e.target.value)}>{scenarioOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className="scenario-description"><Sparkles size={20} /><p>{scenarioOptions.find(([v]) => v === scenario)?.[2]}</p></div>{!charter.active && <p className="inline-note">First, save your agreement to let the agent help within your preferences.</p>}<div className="modal-actions"><button className="button primary" disabled={busy || !charter.active} onClick={async () => { if (await command({ type: 'SIMULATE', scenario })) { setModal(null); navigate('today'); } }}>Run demo scenario <ArrowRight size={16} /></button>{!charter.active && <button className="button secondary" onClick={() => { setModal(null); navigate('agreement'); }}>Make my agreement</button>}</div><div className="modal-bottom"><span>Fixed demo clock · 23 Sep 2026, 6:15 pm IST</span><button className="text-button" onClick={() => setModal('reset')}>Reset sample data</button></div></ModalBox>}
    {modal === 'authorize' && <ModalBox title="Your okay. With clear limits." close={closeModal}><p className="modal-description">You’re authorising simulated actions under agreement v{charter.version}. No real money moves and no live booking is made.</p><dl className="permission-summary"><div><dt>Your mode</dt><dd>{charter.mode === 'recovery' ? 'Recovery credit' : charter.mode === 'stake' ? 'Voluntary stake' : 'No money'}</dd></div><div><dt>Autonomy</dt><dd>{charter.autonomy === 'L2' ? 'L2 · ask before arranging' : 'L3 · act within this agreement'}</dd></div><div><dt>Recovery budget</dt><dd>{money(charter.budgetPaise)} demo credit</dd></div><div><dt>Per action limit</dt><dd>{money(charter.maxActionPaise)}</dd></div>{charter.mode === 'stake' && <div><dt>Voluntary stake</dt><dd>{money(charter.stakePaise)} / miss · {money(charter.weeklyStakeCapPaise)} weekly cap</dd></div>}<div><dt>Allowed actions</dt><dd>{state.actions.filter(a => charter.allowedActionIds.includes(a.id)).map(a => a.title).join(', ') || 'None'}</dd></div><div><dt>Consented evidence</dt><dd>{charter.evidenceSources.map(pretty).join(', ') || 'None'}</dd></div><div><dt>Quiet hours</dt><dd>{charter.quietStart}–{charter.quietEnd} IST</dd></div></dl><p className="fine-print">You can withdraw permission or pause any time. Editing the agreement cancels the existing grant. Uncertain evidence cannot trigger a paid action.</p><div className="modal-actions"><button className="button primary" disabled={busy || !charter.active} onClick={async () => { if (await command({ type: 'AUTHORIZE', accepted: true }, 'Demo permission saved. You’re in control.')) { setModal(null); navigate('today'); } }}><ShieldCheck size={16} /> I authorise this demo agreement</button><button className="text-button" onClick={closeModal}>Not now</button></div></ModalBox>}
    {modal === 'reset' && <ModalBox title="Start with a fresh page?" close={closeModal}><p className="modal-description">This clears the local demo agreement, conversation, events and simulated receipts. Export the activity log first if you want to keep it.</p><div className="modal-actions"><button className="button primary" disabled={busy} onClick={async () => { if (await command({ type: 'RESET_DEMO' }, 'Demo reset. A fresh page is ready.')) { setModal(null); navigate('today'); } }}>Reset local demo</button><button className="button secondary" onClick={closeModal}>Keep my progress</button></div></ModalBox>}
  </div>;
}

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: ReactNode; description: string }) { return <section className="page-intro"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></section>; }

function Agreement({ state, busy, onSave }: { state: AppState; busy: boolean; onSave: (charter: Charter) => Promise<void> }) {
  const [draft, setDraft] = useState<Charter>({ ...state.charter });
  const set = <K extends keyof Charter>(key: K, value: Charter[K]) => setDraft(p => ({ ...p, [key]: value }));
  const toggle = (key: 'days' | 'allowedActionIds' | 'evidenceSources', value: string) => set(key, draft[key].includes(value) ? draft[key].filter(v => v !== value) : [...draft[key], value]);
  const num = (key: 'budgetPaise' | 'maxActionPaise' | 'stakePaise' | 'weeklyStakeCapPaise') => ({ value: draft[key] / 100, onChange: (e: React.ChangeEvent<HTMLInputElement>) => set(key, Math.round(Number(e.target.value) * 100)) });
  const submit = (e: FormEvent) => { e.preventDefault(); void onSave(draft); };
  return <form className="agreement-form" onSubmit={submit}><section className="form-section"><div className="form-section-title"><span>01</span><div><h2>What are you coming back to?</h2><p>Something specific. Something that matters to you.</p></div></div><div className="form-fields two-columns"><label>Your name<input value={draft.name} maxLength={60} required onChange={e => set('name', e.target.value)} /></label><label>Your routine<input value={draft.routine} maxLength={120} required onChange={e => set('routine', e.target.value)} /></label></div><div className="form-fields"><span className="field-label">Your usual days</span><div className="day-picker">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => <button type="button" aria-pressed={draft.days.includes(d)} className={draft.days.includes(d) ? 'active' : ''} key={d} onClick={() => toggle('days', d)}>{d}</button>)}</div></div><div className="form-fields three-columns"><label>Usual time (IST)<input type="time" required value={draft.time} onChange={e => set('time', e.target.value)} /></label><label>Flexibility (minutes)<input type="number" min="0" max="240" required value={draft.flexibilityMinutes} onChange={e => set('flexibilityMinutes', Number(e.target.value))} /></label><label>Small fallback (minutes)<input type="number" min="5" max="60" required value={draft.fallbackMinutes} onChange={e => set('fallbackMinutes', Number(e.target.value))} /></label></div></section>
    <section className="form-section"><div className="form-section-title"><span>02</span><div><h2>How should we help?</h2><p>Pick the kind of support that feels right.</p></div></div><div className="mode-picker">{[{ value: 'recovery' as const, title: 'Recovery credit', text: 'Set aside a little demo credit to make restarting easier.', icon: Wallet }, { value: 'stake' as const, title: 'Voluntary stake', text: 'Choose a bounded, simulated stake for confirmed misses.', icon: ShieldCheck }, { value: 'none' as const, title: 'No money', text: 'Small, free steps. Encouragement without spending.', icon: Heart }].map(m => <label key={m.value} className={draft.mode === m.value ? 'selected' : ''}><input type="radio" name="mode" value={m.value} checked={draft.mode === m.value} onChange={() => set('mode', m.value)} /><m.icon size={21} /><strong>{m.title}</strong><span>{m.text}</span></label>)}</div><div className="form-fields two-columns"><label>Recovery budget (demo ₹)<input type="number" min="0" max="10000" step="1" required {...num('budgetPaise')} /></label><label>Maximum per action (demo ₹)<input type="number" min="0" max="10000" step="1" required {...num('maxActionPaise')} /></label></div>{draft.mode === 'stake' && <div className="form-fields two-columns"><label>Stake per confirmed miss (demo ₹)<input type="number" min="0" max="2000" step="1" required {...num('stakePaise')} /></label><label>Weekly stake cap (demo ₹)<input type="number" min="0" max="10000" step="1" required {...num('weeklyStakeCapPaise')} /></label></div>}<div className="form-fields"><label>How much can the agent do?<select value={draft.autonomy} onChange={e => set('autonomy', e.target.value as Charter['autonomy'])}><option value="L2">L2 · ask me before arranging each action</option><option value="L3">L3 · act within my authorised limits</option></select></label></div><div className="form-fields"><span className="field-label">Actions you allow</span><div className="checkbox-stack">{state.actions.map(a => <label key={a.id}><input type="checkbox" checked={draft.allowedActionIds.includes(a.id)} onChange={() => toggle('allowedActionIds', a.id)} /><div><strong>{a.title}</strong><small>{a.description} · {a.amountPaise ? `${money(a.amountPaise)} demo` : 'Free'}</small></div></label>)}</div></div></section>
    <section className="form-section"><div className="form-section-title"><span>03</span><div><h2>Good support respects a boundary.</h2><p>Your signals, your language, and time that belongs to you.</p></div></div><div className="form-fields"><span className="field-label">Evidence you consent to use</span><div className="checkbox-stack">{[{ value: 'calendar', title: 'Calendar conflicts', description: 'Use simulated meeting signals to offer an easier fallback.' }, { value: 'attendance', title: 'Partner attendance', description: 'Use simulated attendance signals to establish a confirmed miss or completion.' }, { value: 'self_report', title: 'My own check-ins', description: 'Use what I say. Self-reports stay labelled and do not become verified proof.' }].map(e => <label key={e.value}><input type="checkbox" checked={draft.evidenceSources.includes(e.value)} onChange={() => toggle('evidenceSources', e.value)} /><div><strong>{e.title}</strong><small>{e.description}</small></div></label>)}</div></div><div className="form-fields three-columns"><label>Quiet hours start<input type="time" required value={draft.quietStart} onChange={e => set('quietStart', e.target.value)} /></label><label>Quiet hours end<input type="time" required value={draft.quietEnd} onChange={e => set('quietEnd', e.target.value)} /></label><label>Preferred language<select value={draft.language} onChange={e => set('language', e.target.value as Charter['language'])}><option value="en-IN">English</option><option value="hi-IN">Hindi</option><option value="hi-en">Hinglish</option></select></label></div><div className="form-fields"><label>Demo area / address (optional)<input value={draft.address} maxLength={250} onChange={e => set('address', e.target.value)} placeholder="Use a sample area, not your home address" /></label><p className="fine-print">This local demo uses sample signals. No real calendar, attendance or location is connected.</p></div></section><div className="form-submit"><div><ShieldCheck size={17} /><span>Saving creates a new agreement. Payment permission is a separate step.</span></div><button type="submit" className="button primary" disabled={busy || draft.days.length === 0}>{busy ? <LoaderCircle size={16} className="spin" /> : <Check size={16} />} Save my agreement</button></div></form>;
}
